name: Main workflow
on:
  ## This tries to avoid unessesary pushes to forked repo
  ## development branches. No sense in a dev building every
  ## time they push for a PR and no one should be working on
  ## common branches in their fork.
  push:
    branches:
      - master
      - main
      - v[0-9]+.x
      - develop
      - 'hotfix/**'
      - 'release/**'
      - 'feature/**'
  ## Any pull request.
  pull_request:
env:
  DOTNET_NOLOGO: true

jobs:

  test_build_release:
    name: Test, Build, Publish ${{ matrix.package }} on OS ${{ matrix.operating-system }}
    needs: extract_build_info
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        package: [NCI.OCPL.Api.Common, NCI.OCPL.Api.Common.Testing]
    steps:
      - uses: actions/checkout@v2
        ## using latest LTS releases - also it MUST be the SDK version.
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Build with dotnet
        run: dotnet build --configuration Release /WarnAsError
      - name: Unit Tests (with Coverage)
        run: |
              if [ "$RUNNER_OS" == "Windows" ]; then
                dotnet test
              else
                dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=../../${{matrix.package}}.lcov         test/${{matrix.package}}.Tests
              fi
        shell: bash
      - name: Save Code Coverage Output
        uses: actions/upload-artifact@v1
        with:
          name: coverage-api-common-${{ matrix.operating-system }}
          path: ${{matrix.package}}.lcov
        if: matrix.operating-system != 'windows-latest'
      - name: Publish
        run: dotnet publish --configuration Release --output $GITHUB_WORKSPACE/out src/${{matrix.package}}/
        shell: bash
        # Add the NuGet package to the build artifact.
      - name: Create NuGet package for ${{matrix.package}}
        run: |
          dotnet pack --configuration Release --output $GITHUB_WORKSPACE/out src/${{matrix.package}} --include-symbols --include-source
        shell: bash
      - name: Record metadata
        env:
          BUILD_INFO: ${{ toJson( needs.extract_build_info.outputs ) }}
        run: |
          echo "$BUILD_INFO"
          echo "$BUILD_INFO" > $GITHUB_WORKSPACE/out/build-info.json
        shell: bash
      - name: Upload Published Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{matrix.package}}-${{ matrix.operating-system }}
          path: out

  integration_tests:
    name: Run Integration Tests (on Linux)
    runs-on: ubuntu-latest
    needs: test_build_release

    steps:
      - uses: actions/checkout@v2
        ## using latest LTS releases - also it MUST be the SDK version.
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Setup test output directory
        run: |
              ## Create test output and API logging location
              mkdir -p integration-tests/target
        # This project doesn't create an API as a deliverable artifact. In order to test the shared
        # API components, we have to create an API specifically for testing, which means it also has
        # to be built for the express purpose of running the integration tests.
      - name: Build Test Harness
        run: |
              dotnet publish -c Release -o $GITHUB_WORKSPACE/built-api test/integration-test-harness/
      - name: Start API
        env:
          ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS: true
          API_URL: http://localhost:5000
          SLEEP_TIMEOUT: 5
          WAIT_DURATION: 120
          APP_PATH: ./built-api
          APP_ASSEMBLY: integration-test-harness.dll
        run: |
              ## TODO: This should become a GitHub Action.

              ## Start the app and log output
              ## NOTE: We must change directory because while you can call `dotnet "${APP_PATH}/${APP_ASSEMBLY}"`
              ## it will not find the appsettings.json, so we must cd into the APP_PATH first
              cd $APP_PATH && dotnet $APP_ASSEMBLY > ../integration-tests/target/api_log.txt 2>&1 &

              time_waited=1
              echo "Checking status of ${API_URL}."
              until $(curl --output /dev/null --silent --fail ${API_URL}); do
                echo $?

                if [ $time_waited -ge $WAIT_DURATION ]; then
                    echo "Waited past duration. Exiting"
                    exit 1
                fi

                sleep $SLEEP_TIMEOUT
                time_waited=$((time_waited + SLEEP_TIMEOUT))
              done

              echo "API is up"
      - name: Run Integration Test
        ## Normally bash runs with -e which exits the shell upon hitting
        ## an error which breaks our ability to capture those errors.
        shell: bash --noprofile --norc -o pipefail {0}
        run: |
              ## Run Karate
              cd integration-tests && ./bin/karate ./features

              ## Store the exit code off so we can pass this step and
              ## capture the test output in the next step, but still
              ## fail the entire job
              echo TEST_EXIT_CODE=$? >> $GITHUB_ENV
              exit 0
      - name: Upload Integration test results
        uses: actions/upload-artifact@v1
        with:
          name: integration-test-results
          path: integration-tests/target
      - name: Fail build on bad tests
        run: |
              ## Check if we had errors on the test step, and if so, fail the job
              if [ $TEST_EXIT_CODE -ne 0 ]; then
                echo "Tests Failed -- See Run Integration Test step or integration-test-results artifact for more information"
                exit $TEST_EXIT_CODE
              else
                echo "Tests passed"
              fi

  determine_whether_to_publish:

    # This an annoying workaround. Workflows have the ability to conditionally run a job by
    # using job.<job_id>.if and evaluating an expression, but the operations availble in an expression
    # don't allow us to evaluate whether the branch name matches a pattern.
    #
    # Additionally, although individual steps may also run conditionally (jobs.<job_id>.steps[*].if),
    # there's no ability to stop a job, shy of adding a "continue?" condition on every step.
    # So, we end up with an additional job, just for the purpose of deciding whether another job
    # should execute. (And yes, technically that decision could be one of the items exported from the
    # extract_build_info job, but that's inconsistent with the job's definition in the other API workflows.)

    name: Should NuGet packages be published?
    runs-on: windows-latest
    outputs:
      should_publish: ${{ steps.set_outputs.outputs.should_publish }}
    needs:
      - extract_build_info
      - integration_tests

    steps:
      - name: Set outputs
        id: set_outputs
        run: |
          if [[ ${{ github.event_name }}  == 'push' \
            && $(expr match '${{ needs.extract_build_info.outputs.branch_name }}' 'v[0-9]*\.x$') -gt 0 ]]
          then
            SHOULD_PUBLISH=1
          else
            SHOULD_PUBLISH=0
          fi

          echo ${SHOULD_PUBLISH}
          echo ::set-output name=should_publish::${SHOULD_PUBLISH}
        shell: bash


  publish_nuget_packages:

    # Only publish packages if the run was triggered by a push to the version number branch.
    if: ${{ needs.determine_whether_to_publish.outputs.should_publish == 1 }}

    name: Publish ${{matrix.package}} as NuGet package.
    runs-on: windows-latest
    needs:
      - determine_whether_to_publish
      - extract_build_info
      - integration_tests
    env:
      OWNER: ${{ needs.extract_build_info.outputs.repo_owner }}
      SHOULD_RUN: ${{ needs.determine_whether_to_publish.outputs.should_publish }}
    strategy:
      matrix:
        package:
          - NCI.OCPL.Api.Common
          - NCI.OCPL.Api.Common.Testing

    steps:
      - name: Download Published Artifact
        uses: actions/download-artifact@v1
        with:
          name: ${{matrix.package}}-windows-latest
          path: ${{ github.workspace }}
        ## using latest LTS releases - also it MUST be the SDK version.
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
          source-url: "https://nuget.pkg.github.com/${{ env.OWNER }}/index.json"
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        # This outputs a bogus warning that "No API Key was provided and no API Key could be found."
        # This is a bug in the dotnet program and not something wrong with the build process.
        # If this fails with a message saying "Forbidden" and the repository name, check that the
        # repository where the build is taking place matches the one in the .csproj files' <RepositoryUrl> element.
      - name: Publish NuGet package for ${{matrix.package}}
        run: |
          dotnet nuget push ./*.nupkg
        shell: bash


  extract_build_info:
    ## Gather metadata for the build artifact.
    ##
    ## This is done in a separate job because the information is used in multiple locations.
    name: Extract build metadata.
    runs-on: ubuntu-latest
    outputs:
      build_name: ${{ steps.set_outputs.outputs.build_name }}
      branch_name: ${{ steps.set_outputs.outputs.branch_name }}
      commit_hash: ${{ steps.set_outputs.outputs.commit_hash }}
      repo_owner: ${{ steps.set_outputs.outputs.repo_owner }}
      repo_name: ${{ steps.set_outputs.outputs.repo_name }}

    steps:
      - name: Set outputs
        id: set_outputs
        run: |
          ## PUSH
          if [ "${{ github.event_name }}" == "push" ]; then
            BUILD_NAME=$(sed -E 's/refs\/(heads|tags)\///; s/\//__/g;' <<< $GITHUB_REF)
            BRANCH_NAME=$(sed -E 's/refs\/(heads|tags)\///;' <<< $GITHUB_REF)
            COMMIT_HASH=$(echo "${GITHUB_SHA}")
          ## PULL_REQUEST
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            BUILD_NAME=$(echo "pr-${{ github.event.pull_request.number }}")
            BRANCH_NAME=$(echo "pr-${{ github.event.pull_request.number }}")
            COMMIT_HASH=$(echo "${{ github.event.pull_request.head.sha }}")
          else
            ## ERROR
            exit 1
          fi
          ## For step checks and artifact deployment path.
          ## Same for push and PR
          export REPO_FULL=${{ github.repository }}
          export REPO_RE='([^/]+)/(.*)'
          [[ "$REPO_FULL" =~ $REPO_RE ]]
          REPO_OWNER=$(echo "${BASH_REMATCH[1]}")
          REPO_NAME=$(echo "${BASH_REMATCH[2]}")
          ## Set step outputs for later use
          echo ::set-output name=build_name::${BUILD_NAME}
          echo ::set-output name=branch_name::${BRANCH_NAME}
          echo ::set-output name=commit_hash::${COMMIT_HASH}
          echo ::set-output name=repo_owner::${REPO_OWNER}
          echo ::set-output name=repo_name::${REPO_NAME}

